disable update existing jira issues with parameter
prometheus-community/jiralert pull request #150
Opened 2023-02-10 22:05 UTC by dvag-holger-waschke

set update_disabled as paramter to disable the functionality to update exisiting jira issues.. 

we dont want this feature as we have constant monitoring of tickets.

2023-02-17 09:13 UTC, bwplotka requested changes
Thanks! Some nits and good to go!

Curious, what exactly is causing you to want to stop this behaviour? 🤗

2023-02-17 09:13 UTC, bwplotka commented on cmd/jiralert/main.go
> +	updateDisabled = flag.Bool("updateDisabled", false, "if enabled: updates the summary and description of the existing jira issue")
```suggestion
	updateContentDisabled = flag.Bool("update-content-disabled", false, "When true, jiralert does not update the summary and description of the existing jira issue, even when changes are spotted.")
```

2023-02-17 09:13 UTC, bwplotka commented on pkg/notify/notify.go
>  	if issue != nil {
```suggestion
	if issue != nil && !updateDisabled {
```

2023-02-18 01:30 UTC, dvag-holger-waschke commented
> Thanks! Some nits and good to go!
> 
> Curious, what exactly is causing you to want to stop this behaviour? 🤗

Well we have 24/7 team to monitor jira issues and they say they get confused if old issues are being updated which they might have out of sight already. as they are 'customers' for us we deliver them their wishes ;-)

I made some adjustments but they could be to specific for the main branch:

Update function only on the summary of the issue but not on the description -> you see if the alert is resolved at first sight but they dont want constant updates, as we have per example a value as label which is constant changing causing email notifcation flodding.
So I would suggest we leave the changes here as it is and I will keep the fork.

2023-04-13 13:09 UTC, kotarf commented
Is this PR making it into a release any time soon? The current behavior of updating existing tickets renders jiralert completely non-usable by our organization. Thanks.

2023-04-25 13:46 UTC, dvag-holger-waschke commented
I fixed a bug and made the names of the booleans more clear (remove the double negation)

Systemd unit would look like this. If the parameter is not set default is true and the update function works, so its no breaking change. we running this version in production without problems

```bash
[Unit]
Description=Prometheus Jralert Alerting
Documentation=https://github.com/prometheus-community/jiralert
Wants=network-online.target
After=network.target network-online.target

[Service]
Type=simple
User=alertmanager
Group=alertmanager
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/jiralert_1.2 \
  -config /etc/jiralert/config.yml \
  -listen-address 0.0.0.0:9098 \
  -hash-jira-label \
  -update-description=false \
  -update-summary=false \
  -reopen-tickets=false
```

2023-04-25 17:43 UTC, merged