feat(conf): add optional field_labels to override Labels
prometheus-community/jiralert pull request #189
Opened 2024-05-28 21:27 UTC by cropalato

It adds an optional parameter to replace Labels field with a custom field.
It should be enough to fix #164.

2024-05-29 19:41 UTC, cropalato commented
@twotired or @bwplotka Could you please review that?

2025-01-16 08:14 UTC, Marcusfve commented
What about this, is this going to get merged into prometheus alertmanager? Very useful and needed feature for jiralert.

2025-05-23 08:25 UTC, bwplotka requested changes
This is great, thanks!

Some suggestions only

2025-05-23 08:25 UTC, bwplotka commented on pkg/config/config.go
> +// GetJiraFieldKey returns the jira key associated to a field.
Comment is different vs actual function signature -- GetJiraFieldKey only returns error or nil.

2025-05-23 08:25 UTC, bwplotka commented on pkg/config/config.go
> +func (c *Config) GetJiraFieldKey() error {
Do you mind moving this function out of the config.go? It would be epic to separate JIRA API integrations vs config logic. Also let's avoid extra config state that does not belong to user config directly - it's ok to store this fieldkey as variable somewhere.

Also probably you mean `ValidateJIRAField` or something - it's ok to have `validateXYZ` function in cmd/ somewhere 🤔

2025-05-23 08:25 UTC, bwplotka commented on pkg/config/config.go
> +				rc.FieldLabels = "Labels"
We might need constant variable for this

2025-05-23 08:25 UTC, bwplotka commented on pkg/notify/notify.go
> +		labelKey = "labels"
Why not using `labels` as a default value (instead of `Labels`) then?

2025-05-23 08:25 UTC, bwplotka commented on examples/jiralert.yml
> +    field_labels: Labels
Hm, what about `id_field`? 

```suggestion
    # The jira field used by jiralert for the unique hash and optional grouping and static labels that identify the ticket for reuse. It's recommended to keep using labels field, but some users prefer custom fields (see issue #164). Optional (default: labels).
    id_field: labels
```

2025-05-23 08:25 UTC, bwplotka commented on pkg/notify/notify.go
> +		level.Debug(r.logger).Log("msg", "no firing alert; nothing to do.", r.conf.FieldLabels, issueGroupLabel)
Not sure if we should use `IDLabel` value for logging key. What if somebody will have custom field called `msg`? Can we just use `id` here? 

Also I would rename `issueGroupLabel` everywhere to `issueIDLabel` because at this point it might be hash, static and maybe group labels. "Group" is a bit misleading given the `add_group_labels` config field which only referes to Prometheus labels. 🙈 not an ideal name, but not worth changing (unless we want to deprecate)

2025-05-23 08:26 UTC, bwplotka commented
Also please rebase as we updated CI.

2026-04-23 11:24 UTC, SuperQ commented
**This project has been deprecated in favor of [direct alertmanager integration](https://prometheus.io/docs/alerting/latest/configuration/#jira_config).**

2026-04-23 11:24 UTC, closed without merging